# Generated by Django 6.0 on 2026-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_add_super_admin_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['building', 'court_type__name', 'court_number', 'id'], 'verbose_name': '场地', 'verbose_name_plural': '场地'},
        ),
        migrations.AddField(
            model_name='court',
            name='building',
            field=models.CharField(blank=True, choices=[('A', 'A馆'), ('B', 'B馆'), ('C', 'C馆'), ('D', 'D馆'), ('E', 'E馆'), ('F', 'F馆'), ('G', 'G馆'), ('H', 'H馆'), ('I', 'I馆'), ('J', 'J馆'), ('K', 'K馆'), ('L', 'L馆'), ('M', 'M馆'), ('N', 'N馆'), ('O', 'O馆'), ('P', 'P馆'), ('Q', 'Q馆'), ('R', 'R馆'), ('S', 'S馆'), ('T', 'T馆'), ('U', 'U馆'), ('V', 'V馆'), ('W', 'W馆'), ('X', 'X馆'), ('Y', 'Y馆'), ('Z', 'Z馆')], max_length=1, verbose_name='所属场馆'),
        ),
    ]
