# Generated by Django 6.0.6 on 2026-07-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_court_court_number_alter_court_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='教练姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('total_class_hours', models.IntegerField(default=0, verbose_name='课时总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoachStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_hours', models.IntegerField(default=0, verbose_name='授课课时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='booking.coach', verbose_name='教练')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='booking.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '教练学员',
                'verbose_name_plural': '教练学员',
                'unique_together': {('coach', 'student')},
            },
        ),
    ]
