# Generated by Django 6.0.6 on 2026-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_coach_coachstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
